--- #Variable playbook
- hosts: devlinux
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes

  vars:
    pkgname: httpd
    index_path: /var/www/html

  tasks:
    - name: install httpd
      action: yum pkg="{{pkgname}}" state=present

    - name: httpd start
      action: service name="{{pkgname}}" state=started

    - name: deploy index
      action: copy src=index.html dest="{{index_path}}"
