- hosts: devlinux[0]
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:
    - name: git install
      action: yum pkg=git state=present

    - name: httpd install
      action: yum pkg=httpd state=present

    - name: git clone
      ansible.builtin.git:
        repo: https://github.com/anilbichkule/Vel-Assignment.git
        dest: /mnt/ansible
        version: dev

    - name: copy index
      action: copy src=/mnt/ansible/index.html dest=/var/www/html remote_src=yes

    - name: httpd restsrt
      action: service name=httpd state=restarted

- hosts: devlinux[1]
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:
    - name: git install
      action: yum pkg=git state=present

    - name: httpd install
      action: yum pkg=httpd state=present

    - name: git clone
      ansible.builtin.git:
        repo: https://github.com/anilbichkule/Vel-Assignment.git
        dest: /mnt/ansible
        version: qa

    - name: copy index
      action: copy src=/mnt/ansible/index.html dest=/var/www/html remote_src=yes

    - name: httpd restsrt
      action: service name=httpd state=restarted
