- hosts: devlinux[0]
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:
    - name: httpd install
      action: yum pkg=httpd state=present

    - name: git clone
      git:
       repo: https://github.com/anilbichkule/ansible.git
       dest: /home/ansible
       version: dev
 
   - name: copy index
     action: copy src=/home/ansible/Vel-Assignment/index.html dest=/var/www/html

   - name: httpd restsrt
     action: service name=httpd state=restarted

- hosts: devlinux[1]
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:
    - name: httpd install
      action: yum pkg=httpd state=present

    - name: git clone
      git:
       repo: https://github.com/anilbichkule/ansible.git
       dest: /home/ansible
       version: dev

    - name: git clone
      action: git repo=clone https://github.com/anilbichkule/Vel-Assignment.git dest/home/ansible version=qa

    - name: copy index
      action: copy src=/home/ansible/Vel-Assignment/index.html dest=/var/www/html

    - name: httpd restsrt
      action: service name=httpd state=restarted
